version: "3.9"
services:
  backend:
    build: 
      context: ./backend
    ports:
      - 7000:8080
    environment:
      DB_USERNAME: root
      DB_PASSWORD: consensys
      DB_PORT: 27017
      DB_DATABASE: booking_system
      DB_HOST: db
  db:
    image: mongo:5.0.5
    restart: always
    ports:
      - 70:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: consensys
    volumes:
      - .:/data/db
