version: '3.9'
services:
  backend-pepsi:
    build:
      context: ./backend
    ports:
      - 18080:8080
      - 5001
  backend-cola:
    build:
      context: ./backend
    depends_on:
      - backend-pepsi
    ports:
      - 28081:8081
      - 5002
    environment:
      HTTP_PORT: 8081
      P2P_PORT: 5002
      PEERS: ws://backend-pepsi:5001
  backend-consensys:
    build:
      context: ./backend
    depends_on:
      - backend-pepsi
      - backend-cola
    environment:
      HTTP_PORT: 8082
      P2P_PORT: 5003
      PEERS: ws://backend-pepsi:5001,ws://backend-cola:5002
    ports:
      - 18082:8082
  frontend:
    build:
      context: ./frontend
    ports:
      - 13000:3000
    links:
      - 'backend-consensys:be'
